name: Nuitka Build
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'
            cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: on
          include-data-files: |
            ./Dicts/*=Dicts/
            excluded_words.json=excluded_words.json
            config.json=config.json
          enable-plugins: numpy


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: build/main.dist
