name: Nuitka Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'
            cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: on
          include-data-dir: Dicts=Dicts
          include-data-files: |
            excluded_words.json=excluded_words.json
            config.json=config.json

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          body: Action auto release
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: build/*