name: Nuitka Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: |
          gh release create ${{ github.event.inputs.release_tag }} --title "Release ${{ github.event.inputs.release_tag }}" \
          --notes "Action auto release" --draft
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: write
    needs: create

    steps:
      # Check-out repository
      - uses: actions/checkout@v4
        with:
          lfs: true

      # Setup Python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Nuitka build
        run:  |
          pip install nuitka
          python -m spacy download en_core_web_sm
          nuitka --standalone --include-data-dir=Dicts=Dicts --include-data-dir=defaults=defaults --assume-yes-for-downloads --output-dir=build --spacy-language-model=en_core_web_sm --clang --script-name=main.py

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: build/main.dist/*
          args: --ultra-brute
          strip: false


      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: FurLang_server-${{ matrix.os }}.zip
          path: build/main.dist

      - name: Run tree command on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt install tree
          tree

      - name: Release
        run: |
          gh release upload ${{ github.event.inputs.release_tag }} FurLang_server-${{ matrix.os }}.zip
        env:
          GH_TOKEN: ${{ github.token }}


      # - uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ github.event.inputs.release_tag }}
      #     name: Release ${{ github.event.inputs.release_tag }}
      #     body: Action auto release
      #     draft: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     bodyFile: FurLang_server-${{ matrix.os }}.zip
